version: '3.8'
networks:
  uaVlad:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - uaVlad
  backend:
    build:
      context: ./back-end  # Путь к директории с Dockerfile бэкенда
      dockerfile: Dockerfile  # Имя Dockerfile для бэкенда
    ports:
      - "8084:8084"  # Прокси порт 8083 к 8083 на контейнере
    networks:
      - uaVlad
  frontend:
    build:
      context: ./front-end  # Путь к директории с Dockerfile фронтенда
      dockerfile: Dockerfile  # Имя Dockerfile для фронтенда
    ports:
      - "8082:8082"
    depends_on:
      - backend  # Зависимость от бэкенда
    networks:
      - uaVlad
