version: '3'

services:
  frontend:
    env_file:
      - .env
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      uaVlad:
        ipv4_address: ${FRONTEND_IP}

  backend:
    env_file:
      - .env
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      uaVlad:
        ipv4_address: ${BACKEND_IP}

  nginx:
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - frontend
      - backend
    networks:
      uaVlad:
        ipv4_address: ${NGINX_IP}

networks:
  uaVlad:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
