services:
  env_file:
    - .env

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - uaVlad

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      - uaVlad

  nginx:
    image: nginx:latest
    ports:
      - "8085:80"  # маппинг Nginx на внешний порт 8083
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - uaVlad

networks:
  uaVlad:
    driver: bridge
