services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ua-vlad
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tel212140
    networks:
      - uaVlad
  frontend:
    env_file:
      - .env
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - uaVlad

  backend:
    env_file:
      - .env
    environment:
      DJANGO_DB_HOST: db
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      - uaVlad

  nginx:
    image: nginx:latest
    ports:
      - "8085:80"  # маппинг Nginx на внешний порт 8085
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - uaVlad

networks:
  uaVlad:
    driver: bridge
