# Generated by Django 5.1.2 on 2024-10-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('author', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('userName_en', models.CharField(max_length=100, null=True)),
                ('userName_cs', models.CharField(max_length=100, null=True)),
                ('userName_uk', models.CharField(max_length=100, null=True)),
                ('userName_ru', models.CharField(max_length=100, null=True)),
                ('userJob', models.CharField(max_length=255)),
                ('userFoto', models.ImageField(blank=True, null=True, upload_to='team_photos/')),
                ('userSkills', models.TextField()),
                ('userSkills_en', models.TextField(null=True)),
                ('userSkills_cs', models.TextField(null=True)),
                ('userSkills_uk', models.TextField(null=True)),
                ('userSkills_ru', models.TextField(null=True)),
                ('userWhatsApp', models.CharField(blank=True, max_length=50, null=True)),
                ('userTelegram', models.CharField(blank=True, max_length=50, null=True)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userLinkedIn', models.CharField(blank=True, max_length=100, null=True)),
                ('userFB', models.CharField(blank=True, max_length=100, null=True)),
                ('userInst', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
