# Generated by Django 5.1.2 on 2024-10-25 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teamuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='priority',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='userName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='userName_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='userName_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='userName_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='userName_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
