# Generated by Django 5.1.2 on 2024-10-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_comment_active_portfolioitem_active_teamuser_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('browser_language', models.CharField(max_length=10)),
                ('current_date_time', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField()),
                ('platform', models.CharField(max_length=255)),
                ('unique_identifier', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
